server:
  port: 5000
  host: '0.0.0.0'

db:
  url: 'mongodb://mongodb:27017/haufe_test'
  options:
    useNewUrlParser: true,
    useCreateIndex: true,
    useFindAndModify: false,
    useUnifiedTopology: true
