server:
  options:
    port: 5000
    host: '0.0.0.0'
db:
  url: 'mongodb://localhost:27017/haufe_test'
  options:
    useNewUrlParser: true,
    useCreateIndex: true,
    useFindAndModify: false,
    useUnifiedTopology: true
